# Generated by Django 4.1.2 on 2022-11-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='feedback',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='funfact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
