# Generated by Django 4.1.2 on 2022-12-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_student_feedback_alter_student_funfact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photoUrl',
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='/photo/test.jpg', upload_to='photos'),
            preserve_default=False,
        ),
    ]
